
#' Calculate highest intensity charge state
#'
#' @description
#' Calculates the theoretical highest intensity charge state based on a method
#' inspired by Douglass and Venter (dx.doi.org/10.1021/ac401245r).
#'
#' @param sequence Sequence of proteoform to find HICS for. Can only include the 20
#' canonical amino acids.
#' @param height Height to use for cutting tree generated by hierarchical clustering.
#'
#' @return A numeric vector of the theoretical HICS for the provided sequence.
#' @export
#'
#' @examples
#' calculate_HICS("AAAAKAAAA", height = 4)

calculate_HICS <-
   function(
      sequence,
      height = 4
   ) {

      # Accepted amino acids ----------------------------------------------------

      aminoAcids <-
         "RHKDESTNQCGPAVILMFYW" %>%
         stringr::str_split("") %>%
         unlist()

      basicAminoAcids <-
         "RHK" %>%
         stringr::str_split("") %>%
         unlist()


      # Check sequences for non-canonical AA ------------------------------------

      noncanonicalAA <-
         sequence %>%
         purrr::map_lgl(
            ~stringr::str_split(.x, "") %>%
               unlist() %>%
               {!all(. %in% aminoAcids)}
         )

      if (any(noncanonicalAA) == TRUE) {

         warning("One or more sequences include non-canonical AAs (or a spelling error)")

      }

      # Count basic residues ----------------------------------------------------
      # Must have 2 or more to cluster

      enoughBasicResidues <-
         sequence %>%
         purrr::map_int(
            ~stringr::str_count(.x, basicAminoAcids) %>%
               max()
         ) %>%
         purrr::map_lgl(
            ~.x >= 2
         )

      if (any(!enoughBasicResidues) == TRUE) {

         warning("One or more sequences don't have enough basic residues to calculate HICS (should be >=2)")

      }

      # Check if sequences are canonical AND have enough basic residues ---------

      approvedSequence <-
         purrr::map2_lgl(
            !noncanonicalAA,
            enoughBasicResidues,
            ~.x & .y
         )

      # Calculate HICS ----------------------------------------------------------

      suppressWarnings(
         purrr::map_if(
            sequence,
            approvedSequence,
            ~stringr::str_locate_all(.x, basicAminoAcids) %>%
               purrr::reduce(dplyr::union_all) %>%
               unique() %>%
               sort() %>%
               dist() %>%
               hclust() %>%
               cutree(h = height) %>%
               max() %>%
               {. + 1},
            .else = as.integer
         ) %>%
            unlist()
      )

   }

