
#' Predict the highest intensity charge state using hierarchical clustering
#'
#' @description
#' Calculates the theoretical highest intensity charge state based on a method
#' adapted from Douglass and Venter (dx.doi.org/10.1021/ac401245r).
#'
#' @param sequence Vector of sequences of proteoforms to find HICS for. Can only include the 20
#' canonical amino acids.
#' @param height Height to use for cutting tree generated by hierarchical clustering. Effectively, max distance between amino acids considered to be in a single charge "group".
#'
#' @return A numeric vector of the theoretical HICS for the provided sequence.
#' @export
#'
#' @examples
#' predict_HICS_hclust("AAAAKAAAA", height = 3)

predict_HICS_hclust <-
   function(
      sequence,
      height = 3
   ) {

      # Accepted amino acids ----------------------------------------------------

      aminoAcids <-
         "RHKDESTNQCGPAVILMFYW" %>%
         stringr::str_split("") %>%
         unlist()

      basicAminoAcids <-
         "RHK" %>%
         stringr::str_split("") %>%
         unlist()


      # Check sequences for non-canonical AA ------------------------------------

      noncanonicalAA <-
         sequence %>%
         purrr::map_lgl(
            ~stringr::str_split(.x, "") %>%
               unlist() %>%
               {!all(. %in% aminoAcids)}
         )

      if (any(noncanonicalAA) == TRUE) {

         warning("One or more sequences include non-canonical AAs (or a spelling error). Using number of basic residues instead (including N-terminus)")

      }

      # Count basic residues ----------------------------------------------------
      # Must have 2 or more to cluster

      enoughBasicResidues <-
         sequence %>%
         purrr::map_int(
            ~stringr::str_count(.x, basicAminoAcids) %>%
               sum()
         ) %>%
         purrr::map_lgl(
            ~.x >= 1
         )

      if (any(!enoughBasicResidues) == TRUE) {

         warning("One or more sequences don't have enough basic residues to use hierarchical clustering (should be >=1). Using number of basic residues instead (including N-terminus)")

      }

      # Check if sequences are canonical AND have enough basic residues ---------

      approvedSequence <-
         purrr::map2_lgl(
            !noncanonicalAA,
            enoughBasicResidues,
            ~.x & .y
         )

      # Calculate HICS ----------------------------------------------------------

      suppressWarnings(
         purrr::map_if(
            sequence,
            approvedSequence,
            ~stringr::str_locate_all(.x, basicAminoAcids) %>%
               purrr::reduce(dplyr::union_all) %>%
               c(1) %>%
               unique() %>%
               sort() %>%
               dist() %>%
               hclust() %>%
               cutree(h = height) %>%
               max(),
            .else =
               ~sum(stringr::str_count(., basicAminoAcids))+1
         ) %>%
            unlist()
      )

   }

